### ISSUE TITLE
Example code for parseTime and formatTime is buggy

### ISSUE THREAD

**Issue by sbedell** [vaadin/vaadin-time-picker#100]
On the HTML examples page (https://vaadin.com/components/vaadin-time-picker/html-examples/time-picker-advanced-demos#custom-parser-and-formatter), the sample code for setting a new i18n object seems to be buggy. If you try to select 12:00 AM or 12:00 PM it bugs out on you and nothing gets selected. I decided to throw in console.logs to check what's going on. Here are my log statements (I put them right after the function calls):
```javascript
console.log("Calling formatTime", timeObject);
console.log("Calling parseTime ", timeString);
```
And here is the output for selecting 12:00 AM. When you select it, the time picker is still blank as if you haven't selected any time at all. It seems to freak out like it's 12:00 AM, then 12:00 PM, then 24:00, and then it doesn't know what to do with 24. 
Hopefully this is enough info and a fix can be pushed out soon. 

```
18:04:58.776 Calling parseTime  12:00 AM
18:04:58.777 Calling formatTime Object { hours: 12, minutes: "00" }
18:04:58.790 Calling parseTime  12:00 PM 
18:04:58.791 Calling formatTime Object { hours: 24, minutes: "00" }
18:04:58.794 Calling formatTime undefined 
18:04:58.800 Calling parseTime  
18:04:58.800 Calling formatTime undefined
18:04:58.817 Calling parseTime  12:00 AM
18:04:58.818 Calling formatTime Object { hours: 12, minutes: "00" }
18:04:58.821 Calling parseTime  12:00 PM 
18:04:58.821 Calling formatTime Object { hours: 24, minutes: "00" }
18:04:58.822 Calling formatTime undefined
18:04:58.828 Calling parseTime 
18:04:58.828 Calling formatTime undefined
18:04:58.833 Calling parseTime  12:00 AM
18:04:58.833 Calling formatTime Object { hours: 12, minutes: "00" }
18:04:58.837 Calling parseTime  12:00 PM 
18:04:58.837 Calling formatTime Object { hours: 24, minutes: "00" }
18:04:58.838 Calling formatTime undefined
18:04:58.840 Calling parseTime 
18:04:58.840 Calling formatTime undefined
```

**Comment by sbedell** [comment]
I think I figured it out! I basically just had to check for 12 PM (noon) and 12 AM (midnight) as special cases. Here is my fixed code for parseTime. Note that I was *NOT* zero padding the hours like the example code was. Shouldn't really matter though because `parseInt("06") === parseInt("6")` (for example). 

```javascript
parseTime: timeString => {
    // console.log("Calling parseTime ", timeString);
    if (timeString) {
      const parts = /^(\d{1,2})(?::(\d{1,2}))?(?:\s(\w{2}))?$/.exec(timeString);
      let hours;

      if (parts) {
        if (parts[1] === '12' && parts[3] === 'PM') {
          // for 12pm noon, set hours to 12
          hours = 12;              
        } else if (parts[1] === '12' && parts[3] === 'AM') {
          // for 12am midnight, set hours to 0
          hours = 0;
        } else {
          hours = parseInt(parts[1]) + (parts[3] === 'PM' ? 12 : 0);
        }
      }
      
      return parts && {
        hours: hours,
        minutes: parts[2]
      };
    }
  }
```

**Comment by web-padawan** [comment]
Thanks for the issue and sorry about not taking care of it for a while. We will fix that.
