### ISSUE TITLE
setMin and setMax do nothing

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-time-picker#101]
@OlliTietavainenVaadin commented on [Wed Mar 13 2019](https://github.com/vaadin/vaadin-time-picker-flow/issues/27)

`vaadin.version 13.0.1`
Tested on Windows 10,  Chrome

Setting the `min` and `max` values is not working. I'd assume for example the following code:
```
        TimePicker timePicker = new TimePicker();
        timePicker.setMin("10:00");
        timePicker.setValue(LocalTime.NOON);
```
would create a time picker where I can't pick a time earlier than 10 AM, but it doesn't seem to do anything.

Same behavior can also be seen at https://vaadin.com/components/vaadin-time-picker/java-examples

**Comment by denis-anisimov** [comment]
This is apparently a client side issue.
If you open https://vaadin.com/components/vaadin-time-picker/java-examples and use the last Time `Picker With Min And Max Setting` time picker then it behaves as  described.
But you may check that client side `vaadin-time-picker` has both `min`  and `max`  property values.

**Comment by OlliTietavainenVaadin** [comment]
Does not work even in that example for me (Win 10, Chrome):
![image](https://user-images.githubusercontent.com/15027701/54260765-8e72fe80-4572-11e9-9584-6727b586d9cf.png)

**Comment by denis-anisimov** [comment]
Not sure about your latest comment @OlliTietavainenVaadin .
May be my comment was confusing ....

I was trying to say: the issue is confirmed. It's the client side issue. The example works as described in the ticket meaning it works unexpectedly.
But it's not the server side issue since the  `min` and `max` properties have been set from the server side properly:  you may check that client side `vaadin-time-picker` has both min and max property values.
Since the properties are set then now it's responsibility of the client side element to apply them properly.

**Comment by OlliTietavainenVaadin** [comment]
As far as I can tell, the client-side properties haven't been set:
![image](https://user-images.githubusercontent.com/15027701/54261378-553b8e00-4574-11e9-998d-8e572b2397a1.png)

**Comment by denis-anisimov** [comment]
Wrong element @OlliTietavainenVaadin .
I made the same mistake.
Check the tag name.

**Comment by OlliTietavainenVaadin** [comment]
Okay, yeah, you're right. I did notice that `vaadin-time-picker-text-field` should also have `min` attribute: https://github.com/vaadin/vaadin-time-picker/blob/master/src/vaadin-time-picker.html#L60

**Comment by tomivirkki** [comment]
I think it was an issue with V13 having incompatible Flow/Web Component versions tagged at one point. Seems to be working now https://vaadin.com/components/vaadin-time-picker/java-examples
