### ISSUE TITLE
Update bower dependancies

### ISSUE THREAD

**Issue by moderndeveloperllc** [vaadin/vaadin-time-picker#102]
Looks like there are some rather out of date deps. This still points to an old alpha. Bower pulls in the latest, but it's probably not good to have such an old dep.

https://github.com/vaadin/vaadin-time-picker/blob/727328b3812ac49119bfe0c6e0be860728e4b88b/bower.json#L35

**Comment by web-padawan** [comment]
Thanks! Fixed by c413bd8

**Comment by moderndeveloperllc** [comment]
n/p. The things you notice obsessively looking through yarn.lock files...
