### ISSUE TITLE
vaadin-time-picker validity wrong with required attribute

### ISSUE THREAD

**Issue by asyncLiz** [vaadin/vaadin-time-picker#115]
When the time picker is set to required, it passes that attribute along to the text field. When the value changes to something invalid a second time, the text field is marked as valid even though the picker is invalid.

This is because the time picker's invalid property didn't change, so it's not propagating that down the text field, who thinks itself valid since it has a value.

Go to https://vaadin.com/components/vaadin-time-picker/html-examples and add the `required` attribute to an input. Type in "abc" and press enter. The field will be red. Type in "def" and press enter. The field will remove its invalid state.

**Comment by yuriy-fix** [comment]
Fixed via https://github.com/vaadin/vaadin-time-picker/commit/14aee3a670c72a0cb3f305d4c7816771e2c9d339
