### ISSUE TITLE
Component demo base class needs to be renamed

### ISSUE THREAD

**Issue by Haprog** [vaadin/vaadin-time-picker#116]
`ElementDemo` should be named `TimePickerDemo` everywhere so it wouldn't conflict with other element demos in case another one used the same generic name.
Found at least these:
- https://github.com/vaadin/vaadin-time-picker/blob/master/demo/time-picker-demo.js#L1
- https://github.com/vaadin/vaadin-time-picker/blob/master/demo/.eslintrc.json#L5
- https://github.com/vaadin/vaadin-time-picker/blob/master/demo/time-picker-styling-demos.html#L37
- https://github.com/vaadin/vaadin-time-picker/blob/master/demo/time-picker-basic-demos.html#L51
- https://github.com/vaadin/vaadin-time-picker/blob/master/demo/time-picker-advanced-demos.html#L71

**Comment by web-padawan** [comment]
The demo is removed on master and the old demos will not be used by the docs site anymore. Closing.
