### ISSUE TITLE
Input should be typed in from left-to-right in RTL

### ISSUE THREAD

**Issue by DiegoCardoso** [vaadin/vaadin-time-picker#145]
Related to https://github.com/vaadin/vaadin-date-picker-flow/issues/235.

In RTL mode, the values should appear from left-to-right.

#### Expected outcome:

![time-picker-fixed](https://user-images.githubusercontent.com/262432/81157919-23636300-8f90-11ea-9069-35c41043f7cb.gif)

#### Actual outcome:

![time-picker](https://user-images.githubusercontent.com/262432/81157885-1b0b2800-8f90-11ea-9ee3-d0561ee762ce.gif)

**Comment by Haprog** [comment]
@DiegoCardoso Are the "Expected" and "Actual" clips the right way around? Seems contradictory to the description to me.

**Comment by DiegoCardoso** [comment]
Yes. They are in the wrong other. 🤦‍♂️

**Comment by yuriy-fix** [comment]
@shadikhani also specified that overlay should stay in `ltr` mode as well.
