### ISSUE TITLE
serious performance issue.

### ISSUE THREAD

**Issue by bsutton** [vaadin/vaadin-time-picker#165]
I'm building a web component to set a companies office hours.

The component uses use a pair of vaadin-time-picker components for each day, so I have a total of 14 time pickers on the page.

My java class  (HoursForDays.java) binds to the pickers via the @Id annotation.

If I remove the @Id bindings the page loads in about 350ms (using chrome performance tool).

If I add the @Id bindings back in then the load time (to first render) blows out to 6 seconds.

If I replace the time-pickers with combo boxes (just as an experiment) then even with the @Id bindings the page loads in under 1 second.

There appears to be a significant problem with binding the vaadin-time-picker to a java class.

I've attached the relevant files.

[sample.zip](https://github.com/vaadin/vaadin-time-picker-flow/files/2939815/sample.zip)

**Comment by web-padawan** [comment]
Should be fixed by #111. Please submit another issue if you still experience performance problems.
