### ISSUE TITLE
Value should not change when focusing an item, should need enter validation

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-time-picker#30]
Open the time-picker and move item focus with keyboard, then push `tab` the value is changed.
Otherwise `escape` restores previous value

**Comment by jouni** [comment]
As discussed on Slack (related to combo-box and date-picker behavior), this is how we want it to work at the moment. I would close this issue as invalid.

**Comment by manolo** [comment]
No action neede. Working as designed
