### ISSUE TITLE
Plan the combined UX/DX tests

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-time-picker#33]
child of #28

**Comment by YuriyVaadin** [comment]
DX tests: https://gitlab.vaadin.com/elements/dx-tests/merge_requests/6

**Comment by manolo** [comment]
DX tests merged: https://gitlab.vaadin.com/elements/dx-tests/tree/vaadin-time-picker/v1.0.0-alpha1

**Comment by YuriyVaadin** [comment]
DX/UX combined doc: https://docs.google.com/document/d/17YShUzcyDiv-HM_cLiETpDG5wHMLQsQwMviqK5EVGs8/edit#

UX tests guideline was added: https://gitlab.vaadin.com/elements/dx-tests/blob/vaadin-time-picker/v1.0.0-alpha1/ux-tasks.html
