### ISSUE TITLE
Minimum and maximum

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-time-picker#47]
Possibility to set minimum and maximum values for the input / dropdown. In case of keyboard navigation start from minimum, go till maximum and loop. In case of dropdown, show only values in between min and max.

**Comment by samulivaadin** [comment]
This would be great feature for choosing business hours time where it makes no sense to pick anything outside the range.

**Comment by heruan** [comment]
Also useful when selecting a time range with two pickers, where on the second picker should not be possible to select a value lower than the first.

**Comment by pierlon** [comment]
Any comments @tomivirkki @yuriy-fix?
