### ISSUE TITLE
Update step documentation

### ISSUE THREAD

**Issue by yuriy-fix** [vaadin/vaadin-time-picker#49]
Update step documentation with examples, to show users how actually step is applied. Highlight the phrase about setting `step` in seconds and move to the beginning. Add mentioning of the dropdown visibility.

**Comment by sbedell** [comment]
Yup, one of the current examples on the HTML Examples page is showing step="0.5" and it doesn't even work. You need to set step="1800" in order to get half hour (30 * 60 = 1800) intervals. The documentation should reflect that.

**Comment by web-padawan** [comment]
This is what we currently have in the demo:

> The step property specified in seconds affects the resolution of the time picker and visibility of the dropdown. If step is less than 15 mins dropdown is hidden

I think there should be a separate demo with a step big enough to show dropdown.
