### ISSUE TITLE
Overlay is added to DOM even when it is not shown

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-time-picker#58]
When `step` is below 15 mins, the picker/overlay is not used.

But, if you focus the time picker, an invisible overlay is placed in the DOM which blocks interaction with the rest of the page (i.e. the time picker is modal), for no apparent reason. To move the focus to another field requires the user to click twice on that field.

**Comment by web-padawan** [comment]
Reopening per description in vaadin/vaadin-time-picker#63
