### ISSUE TITLE
Pressing Esc twice clears the dropdown list selection but not the visible field value

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-time-picker#73]
Steps to reproduce:

1. Select a value
2. Reopen the dropdown -> the selected value is indicated with a checkmark
2. Press Esc twice
3. Reopen the dropdown -> No item is shown as selected (no checkmark)

**Comment by jouni** [comment]
I think this is probably the same issue as https://github.com/vaadin/vaadin-combo-box/issues/622

**Comment by jouni** [comment]
IMO this is a really nasty bug, as it can quite easily cause unexpected consequences when the user does not realize the value has been cleared.

**Comment by tomivirkki** [comment]
Even after following the steps `timePicker.value` isn't cleared. So this is only visual?

**Comment by jouni** [comment]
Maybe only visual for the time-picker. The internal combo box `selectedItem` is cleared, that’s probably the root cause. The combo box does still also have the correct value.

So I guess the problem is not really in time picker, and only combo box (as time-picker does not have a `selectedItem` property). The potential danger is if a developer binds to the `selectedItem` in combo box.
