### ISSUE TITLE
can't change the background color of [part=input-field]

### ISSUE THREAD

**Issue by andythsu** [vaadin/vaadin-time-picker#90]
I'm using polymer 3.0 with vaadin-time-picker

```
import { PolymerElement, html } from '@polymer/polymer';
import '@vaadin/vaadin-time-picker';

class TimePicker extends PolymerElement{
    static get is(){
        return 'time-picker';
    }
    static get properties(){
        return {
            label: {
                type: String
            }
        };
    }
    static get template(){
        return html`
        <style>
        vaadin-time-picker vaadin-combo-box-light vaadin-time-picker-text-field[part="input-field"]{
            background-color: unset;
        }
        </style>
        <vaadin-time-picker label="{{label}}"></vaadin-time-picker>
        `;
    }
}

customElements.define(TimePicker.is, TimePicker);
```

but it's not changing the background-color of the input-field

I'm assuming the reason is because it's nested in many shadow-doms, so I cannot change its property at the root shadow dom (vaadin-time-picker) ?

**Comment by web-padawan** [comment]
Hi, this is right and you need to use `dom-module` approach to style Vaadin components. 
This is how it looks like in case of the `vaadin-time-picker`:

```js
const styleElement = document.createElement('dom-module');
styleElement.setAttribute('theme-for', 'vaadin-text-field');

styleElement.innerHTML = 
 `<template>
   <style>
      :host([theme="custom-background"]) {
        background-color: unset;
      }
   </style>
 </template>`;

styleElement.register('custom-background'); 
```

and the HTML should look like this:
```html
<vaadin-time-picker theme="custom-background" label="{{label}}"></vaadin-time-picker>
```

See also docs in readme here: https://github.com/vaadin/vaadin-themable-mixin
That's how Vaadin components should be styled in general.

Closing as this is a question, but feel free to add more comments if something is not clear.

**Comment by web-padawan** [comment]
See also working example here: https://glitch.com/edit/#!/flash-sunday?path=custom-theme.js:4:0

**Comment by LeongTitanFour** [comment]
Thank you!
