### ISSUE TITLE
unable to reset value

### ISSUE THREAD

**Issue by punkratz312** [vaadin/vaadin-time-picker#91]
As I use the component inside a form I want to reset its value if the form will be shown again. I wasn´t able to do this. Not by undefining/nulling the corresponding bean property neither not by explicit setting the component´s value property to undefined. If a selection is made the component hold its value forever.

No I´m not going to providing an annoying example. Heres the code where I try to reset the value:

this.$.yazeit.value = null;
delete this.$.yazeit.value;

But the component is not impressed by my efforts, plz help.

Thats the definition:

<vaadin-time-picker required theme="abas-theme" step="900" id="yazeit" label="Beginn" value="{{item.yazeit}}"></vaadin-time-picker>

The behavior is pretty crazy, please fix this or tell my what I´m doing wrong. Thanks a lot.

![image](https://user-images.githubusercontent.com/8830888/51035655-f628bf80-15aa-11e9-847c-d829c8c0b6e5.png)

![image](https://user-images.githubusercontent.com/8830888/51035661-02148180-15ab-11e9-91ad-03445a2a3a82.png)

![image](https://user-images.githubusercontent.com/8830888/51035737-3daf4b80-15ab-11e9-8d74-b9b7fd6a08ce.png)

**Comment by punkratz312** [comment]
plz help

**Comment by web-padawan** [comment]
Thanks for the issue. If you set `value` to empty string instead of null, it works:

```js
this.$.yazeit.value = '';
```

Setting the `null` should clear it as well, though. We will fix that ASAP.

**Comment by punkratz312** [comment]
@web-padawan thanks

**Comment by punkratz312** [comment]
imho strange that settings the corresponding property of the bean, that was bound via 2 way binding, does not affect the component as well.
