### ISSUE TITLE
FormatTime & _GenerateDropdownList  very slow

### ISSUE THREAD

**Issue by ThijsMaenhout** [vaadin/vaadin-time-picker#99]
My dialog uses 8 time-pickers.  When opening the screen for the first time, the timepickers are initialised and their correct locale is set.  However this takes a huge amount of time.  
When doing a performance trace in Chrome, I can see that a lot of time is spent in FormatTime.  It takes about 3 seconds to initialise the pickers.  _GenerateDropdownList takes about 350ms.

I have attached a chrome performance profile.

[Profile-20190304T152219.zip](https://github.com/vaadin/vaadin-time-picker/files/2926734/Profile-20190304T152219.zip)

**Comment by ThijsMaenhout** [comment]
This seems to be the bottleneck:

`        __generateDropdownList() {
          if (this.step < 15 * 60 || !this.__validDayDivisor(this.step)) {
            return [];
          }

          const generatedList = [];

          // Default step in overlay items is 1 hour
          const step = this.step || 3600;

          let time = -step;
          while (time + step < 24 * 60 * 60) {
            const timeObj = this.__validateTime(this.__addStep(time * 1000, step));
            time += step;
            generatedList.push({
              // we only pick items with minute resolution
              label: this.i18n.formatTime(timeObj),
              // but we set value with step defined resolution
              value: this.i18n.formatTime(timeObj)
            });
          }

          return generatedList;
        }`

Would it improve performance by caching label & value so it only has to call formatTime once?

**Comment by web-padawan** [comment]
Thanks for the issue. We will look into it and try to refactor to make it faster.
